import {createHash} from 'node:crypto';
import {v7 as uuidv7} from 'uuid';
import type {DbClient,DbPool} from '../db.js';
import {DomainError} from '../../../../packages/domain/src/index.js';
import type {FakeScript,FakeScriptStep} from '../../../../packages/provider-fake/src/index.js';
import {RoomService,type RunGuard} from '../room-service.js';

const canonical=(value:unknown):unknown=>Array.isArray(value)?value.map(item=>item===undefined?null:canonical(item)):value&&typeof value==='object'?Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([,item])=>item!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,canonical(item)])):value;
const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');
const requiredString=(args:Record<string,unknown>,name:string)=>{const value=args[name];if(typeof value!=='string'||!value.trim())throw new DomainError('provider_output_invalid',`Fake provider tool argument ${name} must be a non-empty string`,422);return value};
const requiredVersion=(args:Record<string,unknown>)=>{const value=args.expected_version;if(typeof value!=='number'||!Number.isInteger(value)||value<1)throw new DomainError('provider_output_invalid','Fake provider expected_version must be a positive integer',422);return value};
const requiredObject=(args:Record<string,unknown>,name:string)=>{const value=args[name];if(!value||typeof value!=='object'||Array.isArray(value))throw new DomainError('provider_output_invalid',`Fake provider tool argument ${name} must be an object`,422);return value as Record<string,unknown>};
const taskStatuses=new Set(['open','in_progress','blocked','awaiting_decision','completed','cancelled']);
export type AgentRunStatus='queued'|'running'|'retry_wait'|'waiting_for_decision'|'completed'|'failed'|'cancelled';
export interface AgentRun {
 id:string;company_id:string;room_id:string;agent_id:string;agent_principal_id:string;task_id:string|null;status:AgentRunStatus;run_generation:number;script:FakeScript;checkpoint_step:number;checkpoint:{step_attempt?:number};attempt_count:number;max_attempts:number;lease_owner:string|null;lease_token:string|null;lease_expires_at:Date|null;error_code:string|null;error_message:string|null;waiting_decision_id:string|null;context_event_seq:number|null;
}
export interface RunLease extends AgentRun {lease_token:string;lease_owner:string;}
interface Principal {id:string;kind:'human'|'agent'|'system';display_name:string;}
export interface Decision {id:string;company_id:string;room_id:string;run_id:string|null;requested_by_principal_id:string;title:string;question:string;rationale:string;proposed_action:Record<string,unknown>;proposed_action_digest:string;status:'pending'|'approved'|'rejected'|'cancelled'|'expired';version:number;resolved_by_principal_id:string|null;resolution_note:string|null;requested_at:Date;resolved_at:Date|null;expires_at:Date|null;}

export class AgentRuntimeService {
 constructor(private readonly pool:DbPool,private readonly rooms:RoomService){}

 private async principal(c:DbClient,companyId:string,principalId:string):Promise<Principal>{const r=await c.query<Principal>(`SELECT id,kind,display_name FROM principals WHERE company_id=$1 AND id=$2 AND status='active'`,[companyId,principalId]);if(!r.rowCount)throw new DomainError('forbidden','Active company principal required',403);return r.rows[0]!}
 private async manager(c:DbClient,companyId:string,roomId:string,principalId:string){const actor=await this.principal(c,companyId,principalId);if(actor.kind!=='human')throw new DomainError('permission_denied','Only a human room manager may resolve decisions',403);const r=await c.query(`SELECT 1 FROM room_members WHERE company_id=$1 AND room_id=$2 AND principal_id=$3 AND status='active' AND role='manager'`,[companyId,roomId,principalId]);if(!r.rowCount)throw new DomainError('permission_denied','Room manager permission required',403);return actor}
 private async appendEvent(c:DbClient,args:{companyId:string;roomId:string;actor:Principal;eventType:string;entityId:string;entityType?:string;entityVersion?:number;payload:unknown;commandId?:string}){
  const seq=await c.query<{last_event_seq:string}>(`UPDATE rooms SET last_event_seq=last_event_seq+1 WHERE company_id=$1 AND id=$2 RETURNING last_event_seq`,[args.companyId,args.roomId]);if(!seq.rowCount)throw new DomainError('room_not_found','Room not found',404);
  const eventId=uuidv7(),commandId=uuidv7(),roomSeq=Number(seq.rows[0]!.last_event_seq);
  const effectiveCommandId=args.commandId??commandId;
  await c.query(`INSERT INTO room_events(id,company_id,room_id,room_seq,event_type,actor_principal_id,actor_kind,actor_display_name,entity_type,entity_id,entity_version,payload,command_id,correlation_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13)`,[eventId,args.companyId,args.roomId,roomSeq,args.eventType,args.actor.id,args.actor.kind,args.actor.display_name,args.entityType??'agent_run',args.entityId,args.entityVersion??null,JSON.stringify(args.payload),effectiveCommandId]);
  await c.query(`SELECT pg_notify('room_events',$1)`,[JSON.stringify({company_id:args.companyId,room_id:args.roomId,room_seq:roomSeq})]);return {event_id:eventId,room_seq:roomSeq,command_id:effectiveCommandId};
 }
 private async cancelPendingDecisionForRun(c:DbClient,args:{companyId:string;roomId:string;runId:string;actor:Principal;reason:string}){const changed=await c.query<{id:string;version:number}>(`UPDATE decisions SET status='cancelled',version=version+1,resolved_by_principal_id=$2,resolution_note=$3,resolved_at=now() WHERE run_id=$1 AND status='pending' RETURNING id,version`,[args.runId,args.actor.id,args.reason]);for(const decision of changed.rows)await this.appendEvent(c,{companyId:args.companyId,roomId:args.roomId,actor:args.actor,eventType:'decision.cancelled',entityType:'decision',entityId:decision.id,entityVersion:decision.version,payload:{decision_id:decision.id,run_id:args.runId,status:'cancelled',version:decision.version,reason:args.reason}})}
 private async priorReceipt<T>(c:DbClient,companyId:string,roomId:string,actorId:string,key:string,type:string,input:unknown){const requestDigest=digest({protocol_version:1,company_id:companyId,room_id:roomId,principal_id:actorId,command_type:type,input});const prior=await c.query<{request_digest:string;response_body:T}>(`SELECT request_digest,response_body FROM command_receipts WHERE company_id=$1 AND room_id=$2 AND principal_id=$3 AND command_type=$4 AND idempotency_key=$5`,[companyId,roomId,actorId,type,key]);if(!prior.rowCount)return {requestDigest};if(prior.rows[0]!.request_digest!==requestDigest)throw new DomainError('idempotency_key_reused','Idempotency key was used with different input',409);return {requestDigest,response:prior.rows[0]!.response_body}}
 private async saveReceipt(c:DbClient,args:{companyId:string;roomId:string;actorId:string;key:string;type:string;requestDigest:string;response:unknown}){await c.query(`INSERT INTO command_receipts(command_id,company_id,room_id,principal_id,idempotency_key,command_type,request_digest,response_status,response_body) VALUES($1,$2,$3,$4,$5,$6,$7,200,$8)`,[uuidv7(),args.companyId,args.roomId,args.actorId,args.key,args.type,args.requestDigest,JSON.stringify(args.response)])}

 async queueRun(input:{companyId:string;roomId:string;actorId:string;agentPrincipalId:string;taskId?:string;script:FakeScript;maxAttempts?:number;idempotencyKey:string}){
  const c=await this.pool.connect();try{await c.query('BEGIN');await this.manager(c,input.companyId,input.roomId,input.actorId);const receipt=await this.priorReceipt<any>(c,input.companyId,input.roomId,input.actorId,input.idempotencyKey,'agent.run.queue',{agentPrincipalId:input.agentPrincipalId,taskId:input.taskId,script:input.script,maxAttempts:input.maxAttempts??3});if(receipt.response){await c.query('COMMIT');return receipt.response}
   const target=await c.query<{agent_id:string;run_generation:number}>(`SELECT p.agent_id,a.run_generation FROM principals p JOIN agents a ON a.company_id=p.company_id AND a.id=p.agent_id JOIN room_members rm ON rm.company_id=p.company_id AND rm.principal_id=p.id AND rm.room_id=$2 AND rm.status='active' WHERE p.company_id=$1 AND p.id=$3 AND p.kind='agent' AND p.status='active' AND a.status='active'`,[input.companyId,input.roomId,input.agentPrincipalId]);if(!target.rowCount)throw new DomainError('agent_unavailable','Active agent principal and room membership required',409);
   if(input.taskId){const task=await c.query(`SELECT 1 FROM tasks WHERE company_id=$1 AND room_id=$2 AND id=$3 AND assignee_principal_id=$4 AND status IN ('open','in_progress','blocked')`,[input.companyId,input.roomId,input.taskId,input.agentPrincipalId]);if(!task.rowCount)throw new DomainError('task_not_eligible','Run task must be active and assigned to this agent',422)}
   const id=uuidv7(),agent=target.rows[0]!;try{await c.query(`INSERT INTO agent_runs(id,company_id,room_id,agent_id,agent_principal_id,task_id,run_generation,script,max_attempts,queued_by_principal_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,input.companyId,input.roomId,agent.agent_id,input.agentPrincipalId,input.taskId??null,agent.run_generation,JSON.stringify(input.script),input.maxAttempts??3,input.actorId])}catch(error:any){if(error?.code==='23505'&&error?.constraint==='agent_runs_one_active_agent_room_idx')throw new DomainError('agent_run_active','This agent already has an active run in this room',409);throw error}
   const actor=await this.principal(c,input.companyId,input.actorId);const event=await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:'agent.run_queued',entityId:id,payload:{run_id:id,agent_principal_id:input.agentPrincipalId,task_id:input.taskId??null,status:'queued'}});const response={id,status:'queued',run_generation:agent.run_generation,...event};await this.saveReceipt(c,{companyId:input.companyId,roomId:input.roomId,actorId:input.actorId,key:input.idempotencyKey,type:'agent.run.queue',requestDigest:receipt.requestDigest,response});await c.query('COMMIT');return response;
  }catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
 }

 async pauseAgent(input:{companyId:string;roomId:string;actorId:string;agentId:string;idempotencyKey:string}){const c=await this.pool.connect();try{await c.query('BEGIN');await this.manager(c,input.companyId,input.roomId,input.actorId);const receipt=await this.priorReceipt<any>(c,input.companyId,input.roomId,input.actorId,input.idempotencyKey,'agent.pause',{agentId:input.agentId});if(receipt.response){await c.query('COMMIT');return receipt.response}const target=await c.query<{principal_id:string;run_generation:number}>(`SELECT p.id principal_id,a.run_generation FROM agents a JOIN principals p ON p.company_id=a.company_id AND p.agent_id=a.id JOIN room_members rm ON rm.company_id=a.company_id AND rm.room_id=$2 AND rm.principal_id=p.id AND rm.status='active' WHERE a.company_id=$1 AND a.id=$3 FOR UPDATE OF a`,[input.companyId,input.roomId,input.agentId]);if(!target.rowCount)throw new DomainError('agent_not_found','Active room agent not found',404);const next=target.rows[0]!.run_generation+1;await c.query(`UPDATE agents SET status='paused',run_generation=$1,version=version+1,updated_at=now() WHERE company_id=$2 AND id=$3`,[next,input.companyId,input.agentId]);const cancelled=await c.query<{id:string;room_id:string}>(`UPDATE agent_runs SET status='cancelled',run_generation=$1,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code='agent_paused',error_message='Agent paused',completed_at=now(),updated_at=now() WHERE company_id=$2 AND agent_id=$3 AND status IN ('queued','running','retry_wait','waiting_for_decision') RETURNING id,room_id`,[next,input.companyId,input.agentId]);const actor=await this.principal(c,input.companyId,input.actorId);for(const run of cancelled.rows){await this.cancelPendingDecisionForRun(c,{companyId:input.companyId,roomId:run.room_id,runId:run.id,actor,reason:'agent_paused'});await this.appendEvent(c,{companyId:input.companyId,roomId:run.room_id,actor,eventType:'agent.run_cancelled',entityId:run.id,payload:{run_id:run.id,status:'cancelled',reason:'agent_paused',run_generation:next}})};const event=await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:'agent.status_changed',entityId:input.agentId,payload:{agent_id:input.agentId,status:'paused',run_generation:next}});const response={agent_id:input.agentId,status:'paused',run_generation:next,...event};await this.saveReceipt(c,{companyId:input.companyId,roomId:input.roomId,actorId:input.actorId,key:input.idempotencyKey,type:'agent.pause',requestDigest:receipt.requestDigest,response});await c.query('COMMIT');return response}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 /** Return a paused agent to service. Manager-only, idempotent, and audited, mirroring pause.
  * Resuming does not queue work: it restores the agent's authority, and an external connector
  * regains Gateway access because its credential check requires an active agent. */
 async resumeAgent(input:{companyId:string;roomId:string;actorId:string;agentId:string;idempotencyKey:string}){const c=await this.pool.connect();try{await c.query('BEGIN');await this.manager(c,input.companyId,input.roomId,input.actorId);const receipt=await this.priorReceipt<any>(c,input.companyId,input.roomId,input.actorId,input.idempotencyKey,'agent.resume',{agentId:input.agentId});if(receipt.response){await c.query('COMMIT');return receipt.response}const target=await c.query<{principal_id:string;status:string;run_generation:number}>(`SELECT p.id principal_id,a.status,a.run_generation FROM agents a JOIN principals p ON p.company_id=a.company_id AND p.agent_id=a.id JOIN room_members rm ON rm.company_id=a.company_id AND rm.room_id=$2 AND rm.principal_id=p.id AND rm.status='active' WHERE a.company_id=$1 AND a.id=$3 FOR UPDATE OF a`,[input.companyId,input.roomId,input.agentId]);if(!target.rowCount)throw new DomainError('agent_not_found','Active room agent not found',404);if(target.rows[0]!.status!=='paused')throw new DomainError('agent_not_paused','Only a paused agent can be resumed',409,{status:target.rows[0]!.status});await c.query(`UPDATE agents SET status='active',version=version+1,updated_at=now() WHERE company_id=$1 AND id=$2`,[input.companyId,input.agentId]);const actor=await this.principal(c,input.companyId,input.actorId);const event=await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:'agent.resumed',entityType:'agent',entityId:input.agentId,payload:{agent_id:input.agentId,agent_principal_id:target.rows[0]!.principal_id,status:'active',run_generation:target.rows[0]!.run_generation}});const response={agent_id:input.agentId,agent_principal_id:target.rows[0]!.principal_id,status:'active',...event};await this.saveReceipt(c,{companyId:input.companyId,roomId:input.roomId,actorId:input.actorId,key:input.idempotencyKey,type:'agent.resume',requestDigest:receipt.requestDigest,response});await c.query('COMMIT');return response}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 async cancelRun(input:{companyId:string;roomId:string;actorId:string;runId:string;idempotencyKey:string}){const c=await this.pool.connect();try{await c.query('BEGIN');await this.manager(c,input.companyId,input.roomId,input.actorId);const receipt=await this.priorReceipt<any>(c,input.companyId,input.roomId,input.actorId,input.idempotencyKey,'agent.run.cancel',{runId:input.runId});if(receipt.response){await c.query('COMMIT');return receipt.response}const run=await c.query<{agent_id:string;run_generation:number}>(`SELECT agent_id,run_generation FROM agent_runs WHERE id=$1 AND company_id=$2 AND room_id=$3 AND status IN ('queued','running','retry_wait','waiting_for_decision') FOR UPDATE`,[input.runId,input.companyId,input.roomId]);if(!run.rowCount)throw new DomainError('run_not_active','Active run not found',409);const next=run.rows[0]!.run_generation+1;await c.query(`UPDATE agent_runs SET status='cancelled',run_generation=$1,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code='cancelled',error_message='Cancelled by manager',completed_at=now(),updated_at=now() WHERE id=$2`,[next,input.runId]);const actor=await this.principal(c,input.companyId,input.actorId);await this.cancelPendingDecisionForRun(c,{companyId:input.companyId,roomId:input.roomId,runId:input.runId,actor,reason:'cancelled_by_manager'});const event=await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:'agent.run_cancelled',entityId:input.runId,payload:{run_id:input.runId,status:'cancelled',run_generation:next}});const response={id:input.runId,status:'cancelled',run_generation:next,...event};await this.saveReceipt(c,{companyId:input.companyId,roomId:input.roomId,actorId:input.actorId,key:input.idempotencyKey,type:'agent.run.cancel',requestDigest:receipt.requestDigest,response});await c.query('COMMIT');return response}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 async reconcileInvalidRuns(){const c=await this.pool.connect();try{await c.query('BEGIN');const invalid=await c.query<AgentRun&{actor_kind:'agent';actor_display_name:string}>(`SELECT ar.*,p.kind actor_kind,p.display_name actor_display_name FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id LEFT JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id AND rm.status='active' WHERE ar.status IN ('queued','running','retry_wait','waiting_for_decision') AND (a.status<>'active' OR p.status<>'active' OR rm.id IS NULL OR a.run_generation<>ar.run_generation) FOR UPDATE OF ar SKIP LOCKED`);for(const run of invalid.rows){const actor={id:run.agent_principal_id,kind:run.actor_kind,display_name:run.actor_display_name};await c.query(`UPDATE agent_runs SET status='cancelled',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code='authority_revoked',error_message='Agent status, membership, or generation changed',completed_at=now(),updated_at=now() WHERE id=$1`,[run.id]);await this.cancelPendingDecisionForRun(c,{companyId:run.company_id,roomId:run.room_id,runId:run.id,actor,reason:'authority_revoked'});await this.appendEvent(c,{companyId:run.company_id,roomId:run.room_id,actor,eventType:'agent.run_cancelled',entityId:run.id,payload:{run_id:run.id,status:'cancelled',reason:'authority_revoked'}})}await c.query('COMMIT');return invalid.rowCount}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 async expireDecisions(){const c=await this.pool.connect();try{await c.query('BEGIN');const expired=await c.query(`SELECT d.*,p.kind actor_kind,p.display_name actor_display_name FROM decisions d JOIN principals p ON p.id=d.requested_by_principal_id WHERE d.status='pending' AND d.expires_at IS NOT NULL AND d.expires_at<=now() FOR UPDATE OF d`);for(const d of expired.rows){await c.query(`UPDATE decisions SET status='expired',version=version+1,resolved_at=now(),resolution_note='Decision expired' WHERE id=$1`,[d.id]);await c.query(`UPDATE agent_runs SET status='cancelled',run_generation=run_generation+1,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code='decision_expired',error_message='Decision expired',completed_at=now(),updated_at=now() WHERE id=$1 AND status='waiting_for_decision'`,[d.run_id]);const actor={id:d.requested_by_principal_id,kind:d.actor_kind,display_name:d.actor_display_name};await this.appendEvent(c,{companyId:d.company_id,roomId:d.room_id,actor,eventType:'decision.expired',entityType:'decision',entityId:d.id,entityVersion:d.version+1,payload:{decision_id:d.id,reason:'deadline_elapsed'}});await this.appendEvent(c,{companyId:d.company_id,roomId:d.room_id,actor,eventType:'agent.run_cancelled',entityId:d.run_id,payload:{reason:'decision_expired',decision_id:d.id}})}await c.query('COMMIT');return expired.rowCount??0}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 async claimNext(workerId:string,leaseMs:number):Promise<RunLease|null>{await this.expireDecisions();await this.reconcileInvalidRuns();const c=await this.pool.connect();try{await c.query('BEGIN');const candidate=await c.query<AgentRun>(`SELECT ar.* FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id AND rm.status='active' WHERE ar.status IN ('queued','running','retry_wait') AND ar.available_at<=now() AND (ar.lease_expires_at IS NULL OR ar.lease_expires_at<now()) AND ar.attempt_count<ar.max_attempts AND a.status='active' AND a.run_generation=ar.run_generation AND p.status='active' ORDER BY ar.created_at FOR UPDATE OF ar SKIP LOCKED LIMIT 1`);if(!candidate.rowCount){await c.query('COMMIT');return null}const previous=candidate.rows[0]!,token=uuidv7();const updated=await c.query<RunLease>(`UPDATE agent_runs SET status='running',lease_owner=$2,lease_token=$3,lease_expires_at=now()+($4::int*interval '1 millisecond'),attempt_count=attempt_count+1,started_at=coalesce(started_at,now()),updated_at=now() WHERE id=$1 RETURNING *`,[previous.id,workerId,token,leaseMs]);const lease=updated.rows[0]!;const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:previous.attempt_count===0?'agent.run_started':'agent.run_resumed',entityId:lease.id,payload:{run_id:lease.id,status:'running',attempt_count:lease.attempt_count,run_generation:lease.run_generation}});await c.query('COMMIT');return lease}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 async renewLease(lease:RunLease,leaseMs:number){const r=await this.pool.query(`UPDATE agent_runs ar SET lease_expires_at=now()+($4::int*interval '1 millisecond'),updated_at=now() FROM agents a,principals p,room_members rm WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.lease_expires_at>now() AND a.company_id=ar.company_id AND a.id=ar.agent_id AND a.status='active' AND a.run_generation=ar.run_generation AND p.company_id=ar.company_id AND p.id=ar.agent_principal_id AND p.status='active' AND rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id AND rm.status='active'`,[lease.id,lease.lease_token,lease.run_generation,leaseMs]);return Boolean(r.rowCount)}
 async getRun(id:string):Promise<AgentRun>{const r=await this.pool.query<AgentRun>(`SELECT * FROM agent_runs WHERE id=$1`,[id]);if(!r.rowCount)throw new DomainError('run_not_found','Agent run not found',404);return r.rows[0]!}
 async contextForRun(id:string){const run=await this.getRun(id);const valid=await this.pool.query(`SELECT 1 FROM agents a JOIN principals p ON p.company_id=a.company_id AND p.agent_id=a.id JOIN room_members rm ON rm.company_id=a.company_id AND rm.principal_id=p.id AND rm.room_id=$2 AND rm.status='active' WHERE a.company_id=$1 AND a.id=$3 AND p.id=$4 AND a.status='active' AND p.status='active' AND a.run_generation=$5`,[run.company_id,run.room_id,run.agent_id,run.agent_principal_id,run.run_generation]);if(!valid.rowCount)throw new DomainError('stale_agent_run','Agent authority changed',409);const snapshot=await this.rooms.snapshot(run.company_id,run.room_id,run.agent_principal_id);const agent=snapshot.members.find((m:any)=>m.principal_id===run.agent_principal_id);const decision=run.waiting_decision_id?(await this.pool.query<Decision>(`SELECT * FROM decisions WHERE id=$1 AND company_id=$2 AND room_id=$3`,[run.waiting_decision_id,run.company_id,run.room_id])).rows[0]??null:null;const changes=run.context_event_seq===null?[]:(await this.pool.query(`SELECT room_seq,event_type,actor_principal_id,actor_kind,actor_display_name,entity_type,entity_id,entity_version,payload,created_at FROM room_events WHERE company_id=$1 AND room_id=$2 AND room_seq>$3 ORDER BY room_seq`,[run.company_id,run.room_id,run.context_event_seq])).rows;return {company_id:run.company_id,room:snapshot.room,agent:{principal_id:run.agent_principal_id,agent_id:run.agent_id,display_name:agent.display_name,responsibilities:agent.responsibilities},project_briefing:snapshot.briefing,assigned_task:snapshot.tasks.find((t:any)=>t.id===run.task_id)??null,eligible_tasks:snapshot.tasks.filter((t:any)=>t.assignee_principal_id===run.agent_principal_id&&!['completed','cancelled'].includes(t.status)),messages:snapshot.messages,decision,room_changes_since_pause:changes}}
 guard(lease:RunLease):RunGuard{return {runId:lease.id,runGeneration:lease.run_generation,leaseToken:lease.lease_token}}
 async executeTool(lease:RunLease,step:Extract<FakeScriptStep,{kind:'tool'}>){const base={companyId:lease.company_id,roomId:lease.room_id,actorId:lease.agent_principal_id,runGuard:this.guard(lease)};const key=`agent-run:${lease.id}:g${lease.run_generation}:${step.id}`;switch(step.name){case 'room.send_message':return this.rooms.sendMessage({...base,body:requiredString(step.arguments,'body'),addressedPrincipalId:step.arguments.addressed_principal_id===undefined?undefined:requiredString(step.arguments,'addressed_principal_id'),taskId:step.arguments.task_id===undefined?undefined:requiredString(step.arguments,'task_id'),idempotencyKey:key});case 'task.get':return this.rooms.getTask({...base,taskId:requiredString(step.arguments,'task_id')});case 'task.list_eligible':return this.rooms.listEligibleTasks(base);case 'task.update_status':{const status=requiredString(step.arguments,'status');if(!taskStatuses.has(status))throw new DomainError('provider_output_invalid','Unsupported task status',422);return this.rooms.updateTaskStatus({...base,taskId:requiredString(step.arguments,'task_id'),status:status as any,expectedVersion:requiredVersion(step.arguments),idempotencyKey:key})}case 'task.complete':return this.rooms.updateTaskStatus({...base,taskId:requiredString(step.arguments,'task_id'),status:'completed',expectedVersion:requiredVersion(step.arguments),idempotencyKey:key});case 'decision.request':return this.requestDecision(lease,step);case 'decision.get':return this.getDecisionForAgent(lease,requiredString(step.arguments,'decision_id'))}}

 async requestDecision(lease:RunLease,step:Extract<FakeScriptStep,{kind:'tool'}>){
  const title=requiredString(step.arguments,'title'),question=requiredString(step.arguments,'question'),rationale=typeof step.arguments.rationale==='string'?step.arguments.rationale:'',proposedAction=requiredObject(step.arguments,'proposed_action'),expiresAt=typeof step.arguments.expires_at==='string'?step.arguments.expires_at:null,actionDigest=digest(proposedAction),key=`agent-run:${lease.id}:g${lease.run_generation}:${step.id}`,input={runId:lease.id,title,question,rationale,proposedAction,proposedActionDigest:actionDigest,expiresAt};if(expiresAt!==null&&Number.isNaN(Date.parse(expiresAt)))throw new DomainError('invalid_decision_expiry','expires_at must be an ISO-8601 timestamp',400);
  const c=await this.pool.connect();try{await c.query('BEGIN');const receipt=await this.priorReceipt<any>(c,lease.company_id,lease.room_id,lease.agent_principal_id,key,'decision.request',input);if(receipt.response){await c.query('COMMIT');return receipt.response}
   const valid=await c.query(`SELECT 1 FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id WHERE ar.id=$1 AND ar.company_id=$2 AND ar.room_id=$3 AND ar.agent_principal_id=$4 AND ar.run_generation=$5 AND ar.lease_token=$6 AND ar.status='running' AND ar.checkpoint_step=$7 AND ar.lease_expires_at>now() AND a.status='active' AND a.run_generation=ar.run_generation AND p.status='active' AND p.kind='agent' AND rm.status='active' AND rm.role='worker_agent' FOR UPDATE OF ar,a,rm`,[lease.id,lease.company_id,lease.room_id,lease.agent_principal_id,lease.run_generation,lease.lease_token,lease.checkpoint_step]);if(!valid.rowCount)throw new DomainError('stale_agent_run','Cannot request a decision from a stale run',409);
   const id=uuidv7();await c.query(`INSERT INTO decisions(id,company_id,room_id,run_id,requested_by_principal_id,title,question,rationale,proposed_action,proposed_action_digest,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,lease.company_id,lease.room_id,lease.id,lease.agent_principal_id,title,question,rationale,JSON.stringify(proposedAction),actionDigest,expiresAt]);const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await pauseCollaborations(c,lease.company_id,lease.room_id,lease.agent_principal_id);const requested=await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:'decision.requested',entityType:'decision',entityId:id,entityVersion:1,payload:{decision_id:id,run_id:lease.id,title,question,rationale,proposed_action:proposedAction,proposed_action_digest:actionDigest,status:'pending',version:1}});const waiting=await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:'agent.run_waiting_for_decision',entityId:lease.id,payload:{run_id:lease.id,decision_id:id,status:'waiting_for_decision',run_generation:lease.run_generation}});
   await c.query(`INSERT INTO agent_tool_calls(id,run_id,company_id,room_id,agent_principal_id,run_generation,step_index,provider_call_id,tool_name,arguments,idempotency_key,status,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'decision.request',$9,$10,'completed',$11)`,[uuidv7(),lease.id,lease.company_id,lease.room_id,lease.agent_principal_id,lease.run_generation,lease.checkpoint_step,step.id,JSON.stringify(step.arguments),key,JSON.stringify({decision_id:id,status:'pending'})]);await c.query(`UPDATE agent_runs SET status='waiting_for_decision',checkpoint_step=checkpoint_step+1,checkpoint='{}'::jsonb,waiting_decision_id=$2,context_event_seq=$3,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1`,[lease.id,id,waiting.room_seq]);const response={id,status:'pending',version:1,run_id:lease.id,proposed_action_digest:actionDigest,waiting_for_decision:true,event_id:requested.event_id,room_seq:waiting.room_seq};await this.saveReceipt(c,{companyId:lease.company_id,roomId:lease.room_id,actorId:lease.agent_principal_id,key,type:'decision.request',requestDigest:receipt.requestDigest,response});await c.query('COMMIT');lease.checkpoint_step++;return response;
  }catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
 }

 async requestExternalDecision(input:{companyId:string;roomId:string;actorId:string;title:string;question:string;rationale?:string;proposedAction:Record<string,unknown>;expiresAt?:string;idempotencyKey:string}){
  const rationale=input.rationale??'',expiresAt=input.expiresAt??null,actionDigest=digest(input.proposedAction);if(expiresAt!==null&&Number.isNaN(Date.parse(expiresAt)))throw new DomainError('invalid_decision_expiry','expires_at must be an ISO-8601 timestamp',400);
  const c=await this.pool.connect();try{await c.query('BEGIN');const receipt=await this.priorReceipt<any>(c,input.companyId,input.roomId,input.actorId,input.idempotencyKey,'decision.request',{title:input.title,question:input.question,rationale,proposedAction:input.proposedAction,proposedActionDigest:actionDigest,expiresAt});if(receipt.response){await c.query('COMMIT');return receipt.response}
   const valid=await c.query(`SELECT 1 FROM principals p JOIN agents a ON a.company_id=p.company_id AND a.id=p.agent_id JOIN room_members rm ON rm.company_id=p.company_id AND rm.principal_id=p.id WHERE p.company_id=$1 AND p.id=$2 AND p.kind='agent' AND p.status='active' AND a.status='active' AND rm.room_id=$3 AND rm.status='active' AND rm.role='worker_agent' FOR UPDATE OF a,rm`,[input.companyId,input.actorId,input.roomId]);if(!valid.rowCount)throw new DomainError('permission_denied','Active worker agent membership is required to request a decision',403);
   const id=uuidv7();await c.query(`INSERT INTO decisions(id,company_id,room_id,run_id,requested_by_principal_id,title,question,rationale,proposed_action,proposed_action_digest,expires_at) VALUES($1,$2,$3,NULL,$4,$5,$6,$7,$8,$9,$10)`,[id,input.companyId,input.roomId,input.actorId,input.title,input.question,rationale,JSON.stringify(input.proposedAction),actionDigest,expiresAt]);const actor=await this.principal(c,input.companyId,input.actorId);await pauseCollaborations(c,input.companyId,input.roomId,input.actorId);const event=await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:'decision.requested',entityType:'decision',entityId:id,entityVersion:1,payload:{decision_id:id,run_id:null,title:input.title,question:input.question,rationale,proposed_action:input.proposedAction,proposed_action_digest:actionDigest,status:'pending',version:1}});const response={id,status:'pending',version:1,run_id:null,proposed_action_digest:actionDigest,event_id:event.event_id,room_seq:event.room_seq};await this.saveReceipt(c,{companyId:input.companyId,roomId:input.roomId,actorId:input.actorId,key:input.idempotencyKey,type:'decision.request',requestDigest:receipt.requestDigest,response});await c.query('COMMIT');return response;
  }catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
 }

 async getDecisionForAgent(lease:RunLease,decisionId:string){const c=await this.pool.connect();try{await c.query('BEGIN');const valid=await c.query(`SELECT 1 FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.lease_expires_at>now() AND a.status='active' AND a.run_generation=ar.run_generation AND p.status='active' AND rm.status='active' FOR UPDATE OF ar`,[lease.id,lease.lease_token,lease.run_generation]);if(!valid.rowCount)throw new DomainError('stale_agent_run','Cannot read a decision from a stale run',409);const result=await c.query<Decision>(`SELECT * FROM decisions WHERE id=$1 AND company_id=$2 AND room_id=$3`,[decisionId,lease.company_id,lease.room_id]);if(!result.rowCount)throw new DomainError('decision_not_found','Decision not found',404);await c.query('COMMIT');return result.rows[0]!}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 async getDecision(input:{companyId:string;roomId:string;actorId:string;decisionId:string}){await this.rooms.snapshot(input.companyId,input.roomId,input.actorId);const result=await this.pool.query<Decision>(`SELECT * FROM decisions WHERE id=$1 AND company_id=$2 AND room_id=$3`,[input.decisionId,input.companyId,input.roomId]);if(!result.rowCount)throw new DomainError('decision_not_found','Decision not found',404);return result.rows[0]!}
 async listDecisions(input:{companyId:string;roomId:string;actorId:string;status?:Decision['status']}){await this.rooms.snapshot(input.companyId,input.roomId,input.actorId);const result=await this.pool.query<Decision>(`SELECT * FROM decisions WHERE company_id=$1 AND room_id=$2 AND ($3::text IS NULL OR status=$3) ORDER BY requested_at DESC`,[input.companyId,input.roomId,input.status??null]);return {decisions:result.rows}}

 async resolveDecision(input:{companyId:string;roomId:string;actorId:string;decisionId:string;resolution:'approved'|'rejected';proposedActionDigest:string;expectedVersion:number;note?:string;idempotencyKey:string}){
  const c=await this.pool.connect();try{await c.query('BEGIN');const actor=await this.manager(c,input.companyId,input.roomId,input.actorId);const receipt=await this.priorReceipt<any>(c,input.companyId,input.roomId,input.actorId,input.idempotencyKey,`decision.${input.resolution}`,{decisionId:input.decisionId,resolution:input.resolution,proposedActionDigest:input.proposedActionDigest,expectedVersion:input.expectedVersion,note:input.note??null});if(receipt.response){await c.query('COMMIT');return receipt.response}
   const current=await c.query<Decision>(`SELECT * FROM decisions WHERE id=$1 AND company_id=$2 AND room_id=$3 FOR UPDATE`,[input.decisionId,input.companyId,input.roomId]);if(!current.rowCount)throw new DomainError('decision_not_found','Decision not found',404);const decision=current.rows[0]!;if(decision.status!=='pending')throw new DomainError('decision_already_resolved','Decision is no longer pending',409,{status:decision.status});if(decision.version!==input.expectedVersion)throw new DomainError('version_conflict','Decision changed since it was read',409,{expected_version:input.expectedVersion,current_version:decision.version});if(decision.proposed_action_digest!==input.proposedActionDigest)throw new DomainError('stale_decision_action','Approval or rejection does not match the exact proposed action',409);
   if(decision.run_id!==null){const resumable=await c.query(`SELECT 1 FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id WHERE ar.id=$1 AND ar.company_id=$2 AND ar.room_id=$3 AND ar.status='waiting_for_decision' AND ar.waiting_decision_id=$4 AND a.status='active' AND a.run_generation=ar.run_generation AND p.status='active' AND rm.status='active' FOR UPDATE OF ar,a,rm`,[decision.run_id,input.companyId,input.roomId,decision.id]);if(!resumable.rowCount)throw new DomainError('decision_run_not_resumable','Waiting agent run is no longer eligible to resume',409)}
   const nextVersion=decision.version+1;await c.query(`UPDATE decisions SET status=$2,version=$3,resolved_by_principal_id=$4,resolution_note=$5,resolved_at=now() WHERE id=$1`,[decision.id,input.resolution,nextVersion,input.actorId,input.note??null]);await resumeCollaborations(c,input.companyId,input.roomId,decision.requested_by_principal_id);const event=await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:`decision.${input.resolution}`,entityType:'decision',entityId:decision.id,entityVersion:nextVersion,payload:{decision_id:decision.id,run_id:decision.run_id,status:input.resolution,version:nextVersion,proposed_action_digest:decision.proposed_action_digest,resolved_by_principal_id:input.actorId,resolution_note:input.note??null}});const runStatus=decision.run_id===null?null:'queued';if(decision.run_id!==null){const resumed=await c.query(`UPDATE agent_runs SET status='queued',available_at=now(),lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code=NULL,error_message=NULL,updated_at=now() WHERE id=$1 AND status='waiting_for_decision' AND waiting_decision_id=$2 RETURNING id`,[decision.run_id,decision.id]);if(!resumed.rowCount)throw new DomainError('decision_run_not_resumable','Waiting agent run was already resumed',409)}const response={id:decision.id,status:input.resolution,version:nextVersion,run_id:decision.run_id,run_status:runStatus,proposed_action_digest:decision.proposed_action_digest,event_id:event.event_id,room_seq:event.room_seq};await this.saveReceipt(c,{companyId:input.companyId,roomId:input.roomId,actorId:input.actorId,key:input.idempotencyKey,type:`decision.${input.resolution}`,requestDigest:receipt.requestDigest,response});await c.query('COMMIT');return response;
  }catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
 }

 async cancelDecision(input:{companyId:string;roomId:string;actorId:string;decisionId:string;expectedVersion:number;idempotencyKey:string}){
  const c=await this.pool.connect();try{await c.query('BEGIN');const actor=await this.manager(c,input.companyId,input.roomId,input.actorId);const receipt=await this.priorReceipt<any>(c,input.companyId,input.roomId,input.actorId,input.idempotencyKey,'decision.cancel',{decisionId:input.decisionId,expectedVersion:input.expectedVersion});if(receipt.response){await c.query('COMMIT');return receipt.response}const current=await c.query<Decision>(`SELECT * FROM decisions WHERE id=$1 AND company_id=$2 AND room_id=$3 FOR UPDATE`,[input.decisionId,input.companyId,input.roomId]);if(!current.rowCount)throw new DomainError('decision_not_found','Decision not found',404);const decision=current.rows[0]!;if(decision.status!=='pending')throw new DomainError('decision_already_resolved','Decision is no longer pending',409,{status:decision.status});if(decision.version!==input.expectedVersion)throw new DomainError('version_conflict','Decision changed since it was read',409,{expected_version:input.expectedVersion,current_version:decision.version});const nextVersion=decision.version+1;await c.query(`UPDATE decisions SET status='cancelled',version=$2,resolved_by_principal_id=$3,resolved_at=now() WHERE id=$1`,[decision.id,nextVersion,input.actorId]);const run=await c.query<{run_generation:number}>(`UPDATE agent_runs SET status='cancelled',run_generation=run_generation+1,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code='decision_cancelled',error_message='Decision cancelled by manager',completed_at=now(),updated_at=now() WHERE id=$1 AND status='waiting_for_decision' AND waiting_decision_id=$2 RETURNING run_generation`,[decision.run_id,decision.id]);const event=await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:'decision.cancelled',entityType:'decision',entityId:decision.id,entityVersion:nextVersion,payload:{decision_id:decision.id,run_id:decision.run_id,status:'cancelled',version:nextVersion}});if(run.rowCount)await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:'agent.run_cancelled',entityId:decision.run_id!,payload:{run_id:decision.run_id,status:'cancelled',reason:'decision_cancelled',run_generation:run.rows[0]!.run_generation}});const response={id:decision.id,status:'cancelled',version:nextVersion,run_id:decision.run_id,run_status:decision.run_id===null?null:'cancelled',event_id:event.event_id,room_seq:event.room_seq};await this.saveReceipt(c,{companyId:input.companyId,roomId:input.roomId,actorId:input.actorId,key:input.idempotencyKey,type:'decision.cancel',requestDigest:receipt.requestDigest,response});await c.query('COMMIT');return response}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
 }

 async checkpoint(lease:RunLease,step:FakeScriptStep,result?:unknown){const c=await this.pool.connect();try{await c.query('BEGIN');const valid=await c.query(`SELECT 1 FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.checkpoint_step=$4 AND ar.lease_expires_at>now() AND a.status='active' AND a.run_generation=ar.run_generation AND p.status='active' AND rm.status='active' FOR UPDATE OF ar,a,rm`,[lease.id,lease.lease_token,lease.run_generation,lease.checkpoint_step]);if(!valid.rowCount)throw new DomainError('stale_agent_run','Cannot checkpoint a stale run',409);if(step.kind==='tool'){const key=`agent-run:${lease.id}:g${lease.run_generation}:${step.id}`;await c.query(`INSERT INTO agent_tool_calls(id,run_id,company_id,room_id,agent_principal_id,run_generation,step_index,provider_call_id,tool_name,arguments,idempotency_key,status,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'completed',$12) ON CONFLICT(run_id,provider_call_id) DO UPDATE SET result=excluded.result,status='completed',completed_at=now()`,[uuidv7(),lease.id,lease.company_id,lease.room_id,lease.agent_principal_id,lease.run_generation,lease.checkpoint_step,step.id,step.name,JSON.stringify(step.arguments),key,JSON.stringify(result??null)])}await c.query(`UPDATE agent_runs SET checkpoint_step=checkpoint_step+1,checkpoint='{}'::jsonb,updated_at=now() WHERE id=$1`,[lease.id]);await c.query('COMMIT');lease.checkpoint_step++;lease.checkpoint={}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async scheduleRetry(lease:RunLease,error:{code:string;message:string},stepAttempt:number){const c=await this.pool.connect();try{await c.query('BEGIN');const current=await c.query<AgentRun>(`SELECT ar.* FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.lease_expires_at>now() AND a.status='active' AND a.run_generation=ar.run_generation AND p.status='active' AND rm.status='active' FOR UPDATE OF ar`,[lease.id,lease.lease_token,lease.run_generation]);if(!current.rowCount){await c.query('COMMIT');return 'cancelled' as const}const exhausted=current.rows[0]!.attempt_count>=current.rows[0]!.max_attempts;if(exhausted){await c.query(`UPDATE agent_runs SET status='failed',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code=$2,error_message=$3,completed_at=now(),updated_at=now() WHERE id=$1`,[lease.id,error.code,error.message]);const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:'agent.run_failed',entityId:lease.id,payload:{run_id:lease.id,status:'failed',error_code:error.code}});await c.query('COMMIT');return 'failed' as const}await c.query(`UPDATE agent_runs SET status='retry_wait',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,checkpoint=jsonb_build_object('step_attempt',$2::int),error_code=$3,error_message=$4,available_at=now(),updated_at=now() WHERE id=$1`,[lease.id,stepAttempt,error.code,error.message]);const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:'agent.run_retry_scheduled',entityId:lease.id,payload:{run_id:lease.id,status:'retry_wait',attempt_count:lease.attempt_count,error_code:error.code}});await c.query('COMMIT');return 'retry_scheduled' as const}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async failRun(lease:RunLease,error:{code:string;message:string}){const c=await this.pool.connect();try{await c.query('BEGIN');const changed=await c.query(`UPDATE agent_runs ar SET status='failed',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code=$4,error_message=$5,completed_at=now(),updated_at=now() FROM agents a,principals p,room_members rm WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.lease_expires_at>now() AND a.company_id=ar.company_id AND a.id=ar.agent_id AND a.status='active' AND a.run_generation=ar.run_generation AND p.company_id=ar.company_id AND p.id=ar.agent_principal_id AND p.status='active' AND rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id AND rm.status='active' RETURNING ar.id`,[lease.id,lease.lease_token,lease.run_generation,error.code,error.message]);if(changed.rowCount){const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:'agent.run_failed',entityId:lease.id,payload:{run_id:lease.id,status:'failed',error_code:error.code}})}await c.query('COMMIT');return changed.rowCount?'failed' as const:'cancelled' as const}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async completeRun(lease:RunLease){const c=await this.pool.connect();try{await c.query('BEGIN');const changed=await c.query(`UPDATE agent_runs ar SET status='completed',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,completed_at=now(),updated_at=now() FROM agents a,principals p,room_members rm WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.lease_expires_at>now() AND a.company_id=ar.company_id AND a.id=ar.agent_id AND a.status='active' AND a.run_generation=ar.run_generation AND p.company_id=ar.company_id AND p.id=ar.agent_principal_id AND p.status='active' AND rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id AND rm.status='active' RETURNING ar.id`,[lease.id,lease.lease_token,lease.run_generation]);if(changed.rowCount){const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:'agent.run_completed',entityId:lease.id,payload:{run_id:lease.id,status:'completed'}})}await c.query('COMMIT');return changed.rowCount?'completed' as const:'cancelled' as const}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
}

/** An agent asking a person to decide stops its collaborations waking anyone until it acts again. */
async function pauseCollaborations(c:{query:(sql:string,params?:unknown[])=>Promise<unknown>},companyId:string,roomId:string,agentPrincipalId:string){
 await c.query(`UPDATE agent_collaborations SET status='waiting_for_human',updated_at=now() WHERE company_id=$1 AND room_id=$2 AND status='active' AND $3::uuid=ANY(participant_principal_ids)`,[companyId,roomId,agentPrincipalId]);
}

/** A decision answered sets the requester's waiting collaborations going again. */
async function resumeCollaborations(c:{query:(sql:string,params?:unknown[])=>Promise<unknown>},companyId:string,roomId:string,agentPrincipalId:string){
 await c.query(`UPDATE agent_collaborations SET status='active',updated_at=now() WHERE company_id=$1 AND room_id=$2 AND status='waiting_for_human' AND $3::uuid=ANY(participant_principal_ids)`,[companyId,roomId,agentPrincipalId]);
}
