import {createHash} from 'node:crypto';
import {v7 as uuidv7} from 'uuid';
import type {DbClient,DbPool} from '../db.js';
import {DomainError} from '../../../../packages/domain/src/index.js';
import type {FakeScript,FakeScriptStep} from '../../../../packages/provider-fake/src/index.js';
import {RoomService,type RunGuard} from '../room-service.js';

const canonical=(value:unknown):unknown=>Array.isArray(value)?value.map(item=>item===undefined?null:canonical(item)):value&&typeof value==='object'?Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([,item])=>item!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,canonical(item)])):value;
const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');
const requiredString=(args:Record<string,unknown>,name:string)=>{const value=args[name];if(typeof value!=='string'||!value.trim())throw new DomainError('provider_output_invalid',`Fake provider tool argument ${name} must be a non-empty string`,422);return value};
const requiredVersion=(args:Record<string,unknown>)=>{const value=args.expected_version;if(typeof value!=='number'||!Number.isInteger(value)||value<1)throw new DomainError('provider_output_invalid','Fake provider expected_version must be a positive integer',422);return value};
const taskStatuses=new Set(['open','in_progress','blocked','awaiting_decision','completed','cancelled']);
export type AgentRunStatus='queued'|'running'|'retry_wait'|'completed'|'failed'|'cancelled';
export interface AgentRun {
 id:string;company_id:string;room_id:string;agent_id:string;agent_principal_id:string;task_id:string|null;status:AgentRunStatus;run_generation:number;script:FakeScript;checkpoint_step:number;checkpoint:{step_attempt?:number};attempt_count:number;max_attempts:number;lease_owner:string|null;lease_token:string|null;lease_expires_at:Date|null;error_code:string|null;error_message:string|null;
}
export interface RunLease extends AgentRun {lease_token:string;lease_owner:string;}
interface Principal {id:string;kind:'human'|'agent'|'system';display_name:string;}

export class AgentRuntimeService {
 constructor(private readonly pool:DbPool,private readonly rooms:RoomService){}

 private async principal(c:DbClient,companyId:string,principalId:string):Promise<Principal>{const r=await c.query<Principal>(`SELECT id,kind,display_name FROM principals WHERE company_id=$1 AND id=$2 AND status='active'`,[companyId,principalId]);if(!r.rowCount)throw new DomainError('forbidden','Active company principal required',403);return r.rows[0]!}
 private async manager(c:DbClient,companyId:string,roomId:string,principalId:string){await this.principal(c,companyId,principalId);const r=await c.query(`SELECT 1 FROM room_members WHERE company_id=$1 AND room_id=$2 AND principal_id=$3 AND status='active' AND role='manager'`,[companyId,roomId,principalId]);if(!r.rowCount)throw new DomainError('permission_denied','Room manager permission required',403)}
 private async appendEvent(c:DbClient,args:{companyId:string;roomId:string;actor:Principal;eventType:string;entityId:string;payload:unknown}){
  const seq=await c.query<{last_event_seq:string}>(`UPDATE rooms SET last_event_seq=last_event_seq+1 WHERE company_id=$1 AND id=$2 RETURNING last_event_seq`,[args.companyId,args.roomId]);if(!seq.rowCount)throw new DomainError('room_not_found','Room not found',404);
  const eventId=uuidv7(),commandId=uuidv7(),roomSeq=Number(seq.rows[0]!.last_event_seq);
  await c.query(`INSERT INTO room_events(id,company_id,room_id,room_seq,event_type,actor_principal_id,actor_kind,actor_display_name,entity_type,entity_id,payload,command_id,correlation_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'agent_run',$9,$10,$11,$11)`,[eventId,args.companyId,args.roomId,roomSeq,args.eventType,args.actor.id,args.actor.kind,args.actor.display_name,args.entityId,JSON.stringify(args.payload),commandId]);
  await c.query(`SELECT pg_notify('room_events',$1)`,[JSON.stringify({company_id:args.companyId,room_id:args.roomId,room_seq:roomSeq})]);return {event_id:eventId,room_seq:roomSeq,command_id:commandId};
 }
 private async priorReceipt<T>(c:DbClient,companyId:string,roomId:string,actorId:string,key:string,type:string,input:unknown){const requestDigest=digest({protocol_version:1,company_id:companyId,room_id:roomId,principal_id:actorId,command_type:type,input});const prior=await c.query<{request_digest:string;response_body:T}>(`SELECT request_digest,response_body FROM command_receipts WHERE company_id=$1 AND room_id=$2 AND principal_id=$3 AND command_type=$4 AND idempotency_key=$5`,[companyId,roomId,actorId,type,key]);if(!prior.rowCount)return {requestDigest};if(prior.rows[0]!.request_digest!==requestDigest)throw new DomainError('idempotency_key_reused','Idempotency key was used with different input',409);return {requestDigest,response:prior.rows[0]!.response_body}}
 private async saveReceipt(c:DbClient,args:{companyId:string;roomId:string;actorId:string;key:string;type:string;requestDigest:string;response:unknown}){await c.query(`INSERT INTO command_receipts(command_id,company_id,room_id,principal_id,idempotency_key,command_type,request_digest,response_status,response_body) VALUES($1,$2,$3,$4,$5,$6,$7,200,$8)`,[uuidv7(),args.companyId,args.roomId,args.actorId,args.key,args.type,args.requestDigest,JSON.stringify(args.response)])}

 async queueRun(input:{companyId:string;roomId:string;actorId:string;agentPrincipalId:string;taskId?:string;script:FakeScript;maxAttempts?:number;idempotencyKey:string}){
  const c=await this.pool.connect();try{await c.query('BEGIN');await this.manager(c,input.companyId,input.roomId,input.actorId);const receipt=await this.priorReceipt<any>(c,input.companyId,input.roomId,input.actorId,input.idempotencyKey,'agent.run.queue',{agentPrincipalId:input.agentPrincipalId,taskId:input.taskId,script:input.script,maxAttempts:input.maxAttempts??3});if(receipt.response){await c.query('COMMIT');return receipt.response}
   const target=await c.query<{agent_id:string;run_generation:number}>(`SELECT p.agent_id,a.run_generation FROM principals p JOIN agents a ON a.company_id=p.company_id AND a.id=p.agent_id JOIN room_members rm ON rm.company_id=p.company_id AND rm.principal_id=p.id AND rm.room_id=$2 AND rm.status='active' WHERE p.company_id=$1 AND p.id=$3 AND p.kind='agent' AND p.status='active' AND a.status='active'`,[input.companyId,input.roomId,input.agentPrincipalId]);if(!target.rowCount)throw new DomainError('agent_unavailable','Active agent principal and room membership required',409);
   if(input.taskId){const task=await c.query(`SELECT 1 FROM tasks WHERE company_id=$1 AND room_id=$2 AND id=$3 AND assignee_principal_id=$4 AND status IN ('open','in_progress','blocked')`,[input.companyId,input.roomId,input.taskId,input.agentPrincipalId]);if(!task.rowCount)throw new DomainError('task_not_eligible','Run task must be active and assigned to this agent',422)}
   const id=uuidv7(),agent=target.rows[0]!;try{await c.query(`INSERT INTO agent_runs(id,company_id,room_id,agent_id,agent_principal_id,task_id,run_generation,script,max_attempts,queued_by_principal_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,input.companyId,input.roomId,agent.agent_id,input.agentPrincipalId,input.taskId??null,agent.run_generation,JSON.stringify(input.script),input.maxAttempts??3,input.actorId])}catch(error:any){if(error?.code==='23505'&&error?.constraint==='agent_runs_one_active_agent_room_idx')throw new DomainError('agent_run_active','This agent already has an active run in this room',409);throw error}
   const actor=await this.principal(c,input.companyId,input.actorId);const event=await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:'agent.run_queued',entityId:id,payload:{run_id:id,agent_principal_id:input.agentPrincipalId,task_id:input.taskId??null,status:'queued'}});const response={id,status:'queued',run_generation:agent.run_generation,...event};await this.saveReceipt(c,{companyId:input.companyId,roomId:input.roomId,actorId:input.actorId,key:input.idempotencyKey,type:'agent.run.queue',requestDigest:receipt.requestDigest,response});await c.query('COMMIT');return response;
  }catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
 }

 async pauseAgent(input:{companyId:string;roomId:string;actorId:string;agentId:string;idempotencyKey:string}){const c=await this.pool.connect();try{await c.query('BEGIN');await this.manager(c,input.companyId,input.roomId,input.actorId);const receipt=await this.priorReceipt<any>(c,input.companyId,input.roomId,input.actorId,input.idempotencyKey,'agent.pause',{agentId:input.agentId});if(receipt.response){await c.query('COMMIT');return receipt.response}const target=await c.query<{principal_id:string;run_generation:number}>(`SELECT p.id principal_id,a.run_generation FROM agents a JOIN principals p ON p.company_id=a.company_id AND p.agent_id=a.id JOIN room_members rm ON rm.company_id=a.company_id AND rm.room_id=$2 AND rm.principal_id=p.id AND rm.status='active' WHERE a.company_id=$1 AND a.id=$3 FOR UPDATE OF a`,[input.companyId,input.roomId,input.agentId]);if(!target.rowCount)throw new DomainError('agent_not_found','Active room agent not found',404);const next=target.rows[0]!.run_generation+1;await c.query(`UPDATE agents SET status='paused',run_generation=$1,version=version+1,updated_at=now() WHERE company_id=$2 AND id=$3`,[next,input.companyId,input.agentId]);const cancelled=await c.query<{id:string;room_id:string}>(`UPDATE agent_runs SET status='cancelled',run_generation=$1,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code='agent_paused',error_message='Agent paused',completed_at=now(),updated_at=now() WHERE company_id=$2 AND agent_id=$3 AND status IN ('queued','running','retry_wait') RETURNING id,room_id`,[next,input.companyId,input.agentId]);const actor=await this.principal(c,input.companyId,input.actorId);for(const run of cancelled.rows)await this.appendEvent(c,{companyId:input.companyId,roomId:run.room_id,actor,eventType:'agent.run_cancelled',entityId:run.id,payload:{run_id:run.id,status:'cancelled',reason:'agent_paused',run_generation:next}});const event=await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:'agent.status_changed',entityId:input.agentId,payload:{agent_id:input.agentId,status:'paused',run_generation:next}});const response={agent_id:input.agentId,status:'paused',run_generation:next,...event};await this.saveReceipt(c,{companyId:input.companyId,roomId:input.roomId,actorId:input.actorId,key:input.idempotencyKey,type:'agent.pause',requestDigest:receipt.requestDigest,response});await c.query('COMMIT');return response}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 async cancelRun(input:{companyId:string;roomId:string;actorId:string;runId:string;idempotencyKey:string}){const c=await this.pool.connect();try{await c.query('BEGIN');await this.manager(c,input.companyId,input.roomId,input.actorId);const receipt=await this.priorReceipt<any>(c,input.companyId,input.roomId,input.actorId,input.idempotencyKey,'agent.run.cancel',{runId:input.runId});if(receipt.response){await c.query('COMMIT');return receipt.response}const run=await c.query<{agent_id:string;run_generation:number}>(`SELECT agent_id,run_generation FROM agent_runs WHERE id=$1 AND company_id=$2 AND room_id=$3 AND status IN ('queued','running','retry_wait') FOR UPDATE`,[input.runId,input.companyId,input.roomId]);if(!run.rowCount)throw new DomainError('run_not_active','Active run not found',409);const next=run.rows[0]!.run_generation+1;await c.query(`UPDATE agent_runs SET status='cancelled',run_generation=$1,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code='cancelled',error_message='Cancelled by manager',completed_at=now(),updated_at=now() WHERE id=$2`,[next,input.runId]);const actor=await this.principal(c,input.companyId,input.actorId);const event=await this.appendEvent(c,{companyId:input.companyId,roomId:input.roomId,actor,eventType:'agent.run_cancelled',entityId:input.runId,payload:{run_id:input.runId,status:'cancelled',run_generation:next}});const response={id:input.runId,status:'cancelled',run_generation:next,...event};await this.saveReceipt(c,{companyId:input.companyId,roomId:input.roomId,actorId:input.actorId,key:input.idempotencyKey,type:'agent.run.cancel',requestDigest:receipt.requestDigest,response});await c.query('COMMIT');return response}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 async reconcileInvalidRuns(){const c=await this.pool.connect();try{await c.query('BEGIN');const invalid=await c.query<AgentRun&{actor_kind:'agent';actor_display_name:string}>(`SELECT ar.*,p.kind actor_kind,p.display_name actor_display_name FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id LEFT JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id AND rm.status='active' WHERE ar.status IN ('queued','running','retry_wait') AND (a.status<>'active' OR p.status<>'active' OR rm.id IS NULL OR a.run_generation<>ar.run_generation) FOR UPDATE OF ar SKIP LOCKED`);for(const run of invalid.rows){await c.query(`UPDATE agent_runs SET status='cancelled',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code='authority_revoked',error_message='Agent status, membership, or generation changed',completed_at=now(),updated_at=now() WHERE id=$1`,[run.id]);await this.appendEvent(c,{companyId:run.company_id,roomId:run.room_id,actor:{id:run.agent_principal_id,kind:run.actor_kind,display_name:run.actor_display_name},eventType:'agent.run_cancelled',entityId:run.id,payload:{run_id:run.id,status:'cancelled',reason:'authority_revoked'}})}await c.query('COMMIT');return invalid.rowCount}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 async claimNext(workerId:string,leaseMs:number):Promise<RunLease|null>{await this.reconcileInvalidRuns();const c=await this.pool.connect();try{await c.query('BEGIN');const candidate=await c.query<AgentRun>(`SELECT ar.* FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id AND rm.status='active' WHERE ar.status IN ('queued','running','retry_wait') AND ar.available_at<=now() AND (ar.lease_expires_at IS NULL OR ar.lease_expires_at<now()) AND ar.attempt_count<ar.max_attempts AND a.status='active' AND a.run_generation=ar.run_generation AND p.status='active' ORDER BY ar.created_at FOR UPDATE OF ar SKIP LOCKED LIMIT 1`);if(!candidate.rowCount){await c.query('COMMIT');return null}const previous=candidate.rows[0]!,token=uuidv7();const updated=await c.query<RunLease>(`UPDATE agent_runs SET status='running',lease_owner=$2,lease_token=$3,lease_expires_at=now()+($4::int*interval '1 millisecond'),attempt_count=attempt_count+1,started_at=coalesce(started_at,now()),updated_at=now() WHERE id=$1 RETURNING *`,[previous.id,workerId,token,leaseMs]);const lease=updated.rows[0]!;const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:previous.attempt_count===0?'agent.run_started':'agent.run_resumed',entityId:lease.id,payload:{run_id:lease.id,status:'running',attempt_count:lease.attempt_count,run_generation:lease.run_generation}});await c.query('COMMIT');return lease}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

 async renewLease(lease:RunLease,leaseMs:number){const r=await this.pool.query(`UPDATE agent_runs ar SET lease_expires_at=now()+($4::int*interval '1 millisecond'),updated_at=now() FROM agents a,principals p,room_members rm WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.lease_expires_at>now() AND a.company_id=ar.company_id AND a.id=ar.agent_id AND a.status='active' AND a.run_generation=ar.run_generation AND p.company_id=ar.company_id AND p.id=ar.agent_principal_id AND p.status='active' AND rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id AND rm.status='active'`,[lease.id,lease.lease_token,lease.run_generation,leaseMs]);return Boolean(r.rowCount)}
 async getRun(id:string):Promise<AgentRun>{const r=await this.pool.query<AgentRun>(`SELECT * FROM agent_runs WHERE id=$1`,[id]);if(!r.rowCount)throw new DomainError('run_not_found','Agent run not found',404);return r.rows[0]!}
 async contextForRun(id:string){const run=await this.getRun(id);const valid=await this.pool.query(`SELECT 1 FROM agents a JOIN principals p ON p.company_id=a.company_id AND p.agent_id=a.id JOIN room_members rm ON rm.company_id=a.company_id AND rm.principal_id=p.id AND rm.room_id=$2 AND rm.status='active' WHERE a.company_id=$1 AND a.id=$3 AND p.id=$4 AND a.status='active' AND p.status='active' AND a.run_generation=$5`,[run.company_id,run.room_id,run.agent_id,run.agent_principal_id,run.run_generation]);if(!valid.rowCount)throw new DomainError('stale_agent_run','Agent authority changed',409);const snapshot=await this.rooms.snapshot(run.company_id,run.room_id,run.agent_principal_id);const agent=snapshot.members.find((m:any)=>m.principal_id===run.agent_principal_id);return {company_id:run.company_id,room:snapshot.room,agent:{principal_id:run.agent_principal_id,agent_id:run.agent_id,display_name:agent.display_name,responsibilities:agent.responsibilities},project_briefing:snapshot.briefing,assigned_task:snapshot.tasks.find((t:any)=>t.id===run.task_id)??null,eligible_tasks:snapshot.tasks.filter((t:any)=>t.assignee_principal_id===run.agent_principal_id&&!['completed','cancelled'].includes(t.status)),messages:snapshot.messages}}
 guard(lease:RunLease):RunGuard{return {runId:lease.id,runGeneration:lease.run_generation,leaseToken:lease.lease_token}}
 async executeTool(lease:RunLease,step:Extract<FakeScriptStep,{kind:'tool'}>){const base={companyId:lease.company_id,roomId:lease.room_id,actorId:lease.agent_principal_id,runGuard:this.guard(lease)};const key=`agent-run:${lease.id}:g${lease.run_generation}:${step.id}`;switch(step.name){case 'room.send_message':return this.rooms.sendMessage({...base,body:requiredString(step.arguments,'body'),addressedPrincipalId:step.arguments.addressed_principal_id===undefined?undefined:requiredString(step.arguments,'addressed_principal_id'),taskId:step.arguments.task_id===undefined?undefined:requiredString(step.arguments,'task_id'),idempotencyKey:key});case 'task.get':return this.rooms.getTask({...base,taskId:requiredString(step.arguments,'task_id')});case 'task.list_eligible':return this.rooms.listEligibleTasks(base);case 'task.update_status':{const status=requiredString(step.arguments,'status');if(!taskStatuses.has(status))throw new DomainError('provider_output_invalid','Unsupported task status',422);return this.rooms.updateTaskStatus({...base,taskId:requiredString(step.arguments,'task_id'),status:status as any,expectedVersion:requiredVersion(step.arguments),idempotencyKey:key})}case 'task.complete':return this.rooms.updateTaskStatus({...base,taskId:requiredString(step.arguments,'task_id'),status:'completed',expectedVersion:requiredVersion(step.arguments),idempotencyKey:key})}}

 async checkpoint(lease:RunLease,step:FakeScriptStep,result?:unknown){const c=await this.pool.connect();try{await c.query('BEGIN');const valid=await c.query(`SELECT 1 FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.checkpoint_step=$4 AND ar.lease_expires_at>now() AND a.status='active' AND a.run_generation=ar.run_generation AND p.status='active' AND rm.status='active' FOR UPDATE OF ar,a,rm`,[lease.id,lease.lease_token,lease.run_generation,lease.checkpoint_step]);if(!valid.rowCount)throw new DomainError('stale_agent_run','Cannot checkpoint a stale run',409);if(step.kind==='tool'){const key=`agent-run:${lease.id}:g${lease.run_generation}:${step.id}`;await c.query(`INSERT INTO agent_tool_calls(id,run_id,company_id,room_id,agent_principal_id,run_generation,step_index,provider_call_id,tool_name,arguments,idempotency_key,status,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'completed',$12) ON CONFLICT(run_id,provider_call_id) DO UPDATE SET result=excluded.result,status='completed',completed_at=now()`,[uuidv7(),lease.id,lease.company_id,lease.room_id,lease.agent_principal_id,lease.run_generation,lease.checkpoint_step,step.id,step.name,JSON.stringify(step.arguments),key,JSON.stringify(result??null)])}await c.query(`UPDATE agent_runs SET checkpoint_step=checkpoint_step+1,checkpoint='{}'::jsonb,updated_at=now() WHERE id=$1`,[lease.id]);await c.query('COMMIT');lease.checkpoint_step++;lease.checkpoint={}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async scheduleRetry(lease:RunLease,error:{code:string;message:string},stepAttempt:number){const c=await this.pool.connect();try{await c.query('BEGIN');const current=await c.query<AgentRun>(`SELECT ar.* FROM agent_runs ar JOIN agents a ON a.company_id=ar.company_id AND a.id=ar.agent_id JOIN principals p ON p.company_id=ar.company_id AND p.id=ar.agent_principal_id JOIN room_members rm ON rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.lease_expires_at>now() AND a.status='active' AND a.run_generation=ar.run_generation AND p.status='active' AND rm.status='active' FOR UPDATE OF ar`,[lease.id,lease.lease_token,lease.run_generation]);if(!current.rowCount){await c.query('COMMIT');return 'cancelled' as const}const exhausted=current.rows[0]!.attempt_count>=current.rows[0]!.max_attempts;if(exhausted){await c.query(`UPDATE agent_runs SET status='failed',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code=$2,error_message=$3,completed_at=now(),updated_at=now() WHERE id=$1`,[lease.id,error.code,error.message]);const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:'agent.run_failed',entityId:lease.id,payload:{run_id:lease.id,status:'failed',error_code:error.code}});await c.query('COMMIT');return 'failed' as const}await c.query(`UPDATE agent_runs SET status='retry_wait',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,checkpoint=jsonb_build_object('step_attempt',$2::int),error_code=$3,error_message=$4,available_at=now(),updated_at=now() WHERE id=$1`,[lease.id,stepAttempt,error.code,error.message]);const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:'agent.run_retry_scheduled',entityId:lease.id,payload:{run_id:lease.id,status:'retry_wait',attempt_count:lease.attempt_count,error_code:error.code}});await c.query('COMMIT');return 'retry_scheduled' as const}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async failRun(lease:RunLease,error:{code:string;message:string}){const c=await this.pool.connect();try{await c.query('BEGIN');const changed=await c.query(`UPDATE agent_runs ar SET status='failed',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,error_code=$4,error_message=$5,completed_at=now(),updated_at=now() FROM agents a,principals p,room_members rm WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.lease_expires_at>now() AND a.company_id=ar.company_id AND a.id=ar.agent_id AND a.status='active' AND a.run_generation=ar.run_generation AND p.company_id=ar.company_id AND p.id=ar.agent_principal_id AND p.status='active' AND rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id AND rm.status='active' RETURNING ar.id`,[lease.id,lease.lease_token,lease.run_generation,error.code,error.message]);if(changed.rowCount){const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:'agent.run_failed',entityId:lease.id,payload:{run_id:lease.id,status:'failed',error_code:error.code}})}await c.query('COMMIT');return changed.rowCount?'failed' as const:'cancelled' as const}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async completeRun(lease:RunLease){const c=await this.pool.connect();try{await c.query('BEGIN');const changed=await c.query(`UPDATE agent_runs ar SET status='completed',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,completed_at=now(),updated_at=now() FROM agents a,principals p,room_members rm WHERE ar.id=$1 AND ar.lease_token=$2 AND ar.run_generation=$3 AND ar.status='running' AND ar.lease_expires_at>now() AND a.company_id=ar.company_id AND a.id=ar.agent_id AND a.status='active' AND a.run_generation=ar.run_generation AND p.company_id=ar.company_id AND p.id=ar.agent_principal_id AND p.status='active' AND rm.company_id=ar.company_id AND rm.room_id=ar.room_id AND rm.principal_id=ar.agent_principal_id AND rm.status='active' RETURNING ar.id`,[lease.id,lease.lease_token,lease.run_generation]);if(changed.rowCount){const actor=await this.principal(c,lease.company_id,lease.agent_principal_id);await this.appendEvent(c,{companyId:lease.company_id,roomId:lease.room_id,actor,eventType:'agent.run_completed',entityId:lease.id,payload:{run_id:lease.id,status:'completed'}})}await c.query('COMMIT');return changed.rowCount?'completed' as const:'cancelled' as const}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
}
