import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { generatedFiles, sendGeneratedMessage, verifyGeneratedDelivery, type GeneratedOutput, type GatewayClient } from '../packages/connector-core/src/index.js';

const roots: string[] = [];
function fixture() {
  const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'output-boundary-')));
  roots.push(root);
  const output: GeneratedOutput = { directory: path.join(root, 'files'), manifest: path.join(root, 'manifest.json'), receipts: path.join(root, 'receipts') };
  fs.mkdirSync(output.directory);
  fs.writeFileSync(output.manifest, JSON.stringify({ expected: [] }));
  return { root, output };
}
afterEach(() => { roots.splice(0).forEach(root => fs.rmSync(root, { recursive: true, force: true })); });

describe('invocation output security boundary', () => {
  it('ignores outside files even when prose names them', async () => {
    const { root, output } = fixture();
    const outside = path.join(root, 'secret.txt');
    fs.writeFileSync(outside, 'private');
    let uploads = 0;
    let sent: any;
    const client = { uploadArtifact: async () => { uploads++; return { id: 'unexpected' }; }, sendMessage: async (input: any) => { sent = input; return {}; } } as unknown as GatewayClient;
    await expect(sendGeneratedMessage(client, output, { body: `Saved to ${outside}` }, 'key', 'scope')).rejects.toThrow('Local file paths are not delivery');
    expect(uploads).toBe(0);
    expect(sent).toBeUndefined();
  });
  it.each(['symlink', 'hardlink', 'directory', 'empty', 'missing', 'traversal'])('refuses %s without uploading or sending', async mode => {
    const { root, output } = fixture();
    const outside = path.join(root, 'secret.txt');
    const target = path.join(output.directory, 'report.pdf');
    fs.writeFileSync(outside, 'private');
    if (mode === 'symlink') fs.symlinkSync(outside, target);
    if (mode === 'hardlink') fs.linkSync(outside, target);
    if (mode === 'directory') fs.mkdirSync(target);
    if (mode === 'empty') fs.writeFileSync(target, '');
    if (mode === 'missing' || mode === 'traversal') fs.writeFileSync(output.manifest, JSON.stringify({ expected: [mode === 'missing' ? 'report.pdf' : '../secret.txt'] }));
    let calls = 0;
    const client = { uploadArtifact: async () => { calls++; }, sendMessage: async () => { calls++; } } as unknown as GatewayClient;
    await expect(sendGeneratedMessage(client, output, { body: 'Done' }, 'key', 'scope')).rejects.toThrow();
    expect(calls).toBe(0);
  });
  it('allows a missing deliverable to be created and retried with the same key', async () => {
    const { output } = fixture();
    fs.writeFileSync(output.manifest, JSON.stringify({ expected: ['report.pdf'] }));
    let sent: any, uploads = 0;
    const client = { uploadArtifact: async () => { uploads++; return { id: 'pdf-one' }; }, sendMessage: async (input: any) => { sent = input; return {}; } } as unknown as GatewayClient;
    const input = { body: `Here is ${path.join(output.directory, 'report.pdf')}` };
    await expect(sendGeneratedMessage(client, output, input, 'retry-key', 'scope')).rejects.toThrow('missing');
    fs.writeFileSync(path.join(output.directory, 'report.pdf'), '%PDF-1.4');
    await sendGeneratedMessage(client, output, input, 'retry-key', 'scope');
    expect(uploads).toBe(1);
    expect(sent).toEqual({ body: 'Here is report.pdf', artifactIds: ['pdf-one'] });
  });
  it('refuses a replaced output directory and undelivered generated bytes', () => {
    const { root, output } = fixture();
    fs.writeFileSync(path.join(output.directory, 'report.pdf'), '%PDF-1.4');
    expect(() => verifyGeneratedDelivery(output)).toThrow('not delivered');
    fs.renameSync(output.directory, path.join(root, 'other'));
    fs.symlinkSync(path.join(root, 'other'), output.directory);
    expect(() => generatedFiles(output)).toThrow('symlink');
  });
  it('fences concurrent same-key sends, and replays the prepared payload after a lost message response without reupload', async () => {
    const { output } = fixture();
    fs.writeFileSync(path.join(output.directory, 'report.pdf'), '%PDF-1.4');
    let uploads = 0, messages = 0;
    let release!: () => void;
    const waiting = new Promise<void>(resolve => { release = resolve; });
    const client = {
      uploadArtifact: async () => { uploads++; await waiting; return { id: 'artifact-one' }; },
      sendMessage: async (input: any) => { messages++; expect(input.artifactIds).toEqual(['artifact-one']); if (messages === 1) throw new Error('lost response'); return {}; },
    } as unknown as GatewayClient;
    const first = sendGeneratedMessage(client, output, { body: 'Done' }, 'same-key', 'scope');
    await expect(sendGeneratedMessage(client, output, { body: 'Done' }, 'same-key', 'scope')).rejects.toThrow('refusing retransmission');
    release();
    await expect(first).rejects.toThrow('lost response');
    await sendGeneratedMessage(client, output, { body: 'Done' }, 'same-key', 'scope');
    expect(uploads).toBe(1);
    expect(messages).toBe(2);
    expect(() => verifyGeneratedDelivery(output)).not.toThrow();
    await expect(sendGeneratedMessage(client, output, { body: 'Changed' }, 'same-key', 'scope')).rejects.toThrow('different message');
  });
});
