import React from 'react';
import {createRoot} from 'react-dom/client';
import {AttachmentCard} from '../../apps/web/src/Attachments';

// Disposable PDF bytes are generated by the native test; no API, identity or model is used.
const root=createRoot(document.getElementById('root')!);
Object.assign(window,{
  pdfFixtureReady:true,
  showLegacyPDF:(encoded:string,sandbox:boolean)=>{
    const bytes=new Blob([Uint8Array.from(atob(encoded),c=>c.charCodeAt(0))],{type:'application/pdf'});
    const url=URL.createObjectURL(bytes);
    const dialog=document.createElement('dialog');dialog.className='file-preview';
    const header=document.createElement('header');header.textContent='Baseline sandbox blob PDF preview';dialog.append(header);
    const frame=document.createElement('iframe');frame.title='Baseline PDF';if(sandbox)frame.setAttribute('sandbox','');frame.src=url;dialog.append(frame);
    document.body.append(dialog);dialog.showModal();
    return true;
  },
  clearLegacyPDF:()=>{const dialog=document.querySelector('dialog');const url=dialog?.querySelector('iframe')?.src;dialog?.remove();if(url)URL.revokeObjectURL(url)},
  setPDFFixture:(encoded:string)=>{
    const bytes=new Blob([Uint8Array.from(atob(encoded),c=>c.charCodeAt(0))],{type:'application/pdf'});
    root.render(<AttachmentCard artifact={{id:'synthetic-pdf',filename:'Two-page PDF regression.pdf',content_type:'application/pdf',byte_size:bytes.size}} api={{artifactBytes:async()=>bytes}}/>);
  },
});
